### ISSUE TITLE
automated testing plan v1

### ISSUE THREAD

**Issue by andrewsu** [NCATSTranslator/TACT#8]
Based on the 2024-02-08 TACT meeting, the Testing group is seeking approval for a first version of the automated testing plan.  The live document is at https://docs.google.com/document/d/1bQWQzbDg-L8o4D7yBU1xlkO_AOLDQZUIFg_Uh-PWFDI/edit#bookmark=id.y420lmlco9fj (with clickable links) and the screenshot below confirms the specific version we are seeking approval on.  

![image](https://github.com/NCATSTranslator/TACT/assets/2635409/2f7904ee-e107-45df-855b-219d1a550e9a)

**Comment by tursynay** [comment]
@NCATSTranslator/tact-voting-members, please review and give a 👍 to this Test Run Plan that was presented at the TACT call on Feb 8. 

**Deadline to review and provide a 👍 or voice your concern is by eob Feb 15.**

**Comment by karafecho** [comment]
@andrewsu @ShervinAbd92 : Max and I posted comments on the live doc. Please take a look and see if these should be addressed before we finalize the vote. Thanks!

**Comment by andrewsu** [comment]
thanks @karafecho, I believe that comment and others have now been updated and resolved. Please continue with adding 👍 and 👎 above!

**Comment by andrewsu** [comment]
Approved on TACT call 2024-02-22

**Comment by saramsey** [comment]
approved.
